// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQTQJkYgeLQy2oc5WK51fgCROXSVIwtfg',
    appId: '1:61261560237:web:286ffce455ce0846384924',
    messagingSenderId: '61261560237',
    projectId: 'moyeo-22a63',
    authDomain: 'moyeo-22a63.firebaseapp.com',
    storageBucket: 'moyeo-22a63.appspot.com',
    measurementId: 'G-7QE82HP2TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-38nKUukvRH0DuiAXolv3vYb4xShcDEE',
    appId: '1:61261560237:android:3af717b1524c3333384924',
    messagingSenderId: '61261560237',
    projectId: 'moyeo-22a63',
    storageBucket: 'moyeo-22a63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkaLlXL-AREnjbXQ53o8OV39UTM_--0ko',
    appId: '1:61261560237:ios:5f5fe3131065666e384924',
    messagingSenderId: '61261560237',
    projectId: 'moyeo-22a63',
    storageBucket: 'moyeo-22a63.appspot.com',
    iosClientId: '61261560237-pp5nfg37cbpn43avot2fbfv7d0tcbd47.apps.googleusercontent.com',
    iosBundleId: 'com.danim.danim',
  );
}
