// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvizYfeV0DmTEl44_dJPHZnEn0NZSHDvs',
    appId: '1:122204542406:web:2856001d479708931f8ec7',
    messagingSenderId: '122204542406',
    projectId: 'moyeo-68d53',
    authDomain: 'moyeo-68d53.firebaseapp.com',
    storageBucket: 'moyeo-68d53.appspot.com',
    measurementId: 'G-WWQ7NXF5M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDElB5HGx02Px1DUhaQn54sEWvOzMwQ4D8',
    appId: '1:122204542406:android:47617dde014541331f8ec7',
    messagingSenderId: '122204542406',
    projectId: 'moyeo-68d53',
    storageBucket: 'moyeo-68d53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpspLBDsWr3UMPf4KZD_KscTaEPeZhofM',
    appId: '1:122204542406:ios:defad81c5c4a8f441f8ec7',
    messagingSenderId: '122204542406',
    projectId: 'moyeo-68d53',
    storageBucket: 'moyeo-68d53.appspot.com',
    iosClientId: '122204542406-4sq9g93007d6n8vsmufk4h56fh5gdsia.apps.googleusercontent.com',
    iosBundleId: 'com.danim.danim',
  );
}
